version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  order_service:
    build: ./order_service
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  logistics_service:
    build: ./logistics_service
    depends_on:
      - rabbitmq